INSERT INTO derivaciones (usuario_id, alumno_id, motivo, urgencia, recibido, created_at, updated_at)
VALUES
(10, 40, 'Dificultades de concentración en clases', 'BAJA', FALSE, NOW(), NOW()),
(11, 41, 'Ansiedad por evaluaciones frecuentes', 'MEDIA', TRUE, NOW(), NOW()),
(12, 42, 'Problemas de conducta en el aula', 'ALTA', FALSE, NOW(), NOW()),
(13, 43, 'Falta de motivación para continuar estudios', 'BAJA', FALSE, NOW(), NOW()),
(14, 44, 'Conflictos con compañeros de clase', 'MEDIA', TRUE, NOW(), NOW()),
(15, 45, 'Se observa aislamiento social', 'ALTA', FALSE, NOW(), NOW()),
(10, 46, 'Dificultades para adaptarse al nuevo entorno académico', 'BAJA', TRUE, NOW(), NOW()),
(11, 47, 'Expresiones de estrés y cansancio frecuente', 'MEDIA', FALSE, NOW(), NOW()),
(12, 48, 'Posible depresión detectada por docente', 'ALTA', TRUE, NOW(), NOW()),
(13, 49, 'Problemas familiares que afectan su desempeño', 'BAJA', FALSE, NOW(), NOW()),
(14, 50, 'Falta de asistencia recurrente sin justificación', 'MEDIA', TRUE, NOW(), NOW()),
(15, 51, 'Bajo rendimiento académico sostenido', 'ALTA', FALSE, NOW(), NOW()),
(10, 52, 'Se observa agresividad hacia compañeros', 'BAJA', TRUE, NOW(), NOW()),
(11, 53, 'Alumno con dificultades de integración en grupo', 'MEDIA', FALSE, NOW(), NOW()),
(12, 54, 'Episodios de ansiedad en presentaciones orales', 'ALTA', TRUE, NOW(), NOW()),
(13, 55, 'Dificultad para expresar emociones', 'BAJA', FALSE, NOW(), NOW()),
(14, 56, 'Alumno manifiesta problemas de autoestima', 'MEDIA', TRUE, NOW(), NOW()),
(15, 57, 'Reportes de insomnio y fatiga constante', 'ALTA', FALSE, NOW(), NOW()),
(10, 58, 'Conflictos con docentes en clase', 'BAJA', TRUE, NOW(), NOW()),
(11, 59, 'Se percibe desinterés generalizado', 'MEDIA', FALSE, NOW(), NOW()),
(12, 60, 'Alumno con antecedentes de problemas psicológicos', 'ALTA', TRUE, NOW(), NOW()),
(13, 40, 'Necesita apoyo para manejo de frustración', 'BAJA', FALSE, NOW(), NOW()),
(14, 41, 'Alumno refiere problemas económicos que afectan su ánimo', 'MEDIA', TRUE, NOW(), NOW()),
(15, 42, 'Se detectan signos de estrés académico', 'ALTA', FALSE, NOW(), NOW()),
(10, 43, 'Alumno presenta pensamientos negativos recurrentes', 'BAJA', TRUE, NOW(), NOW()),
(11, 44, 'Conductas disruptivas dentro del salón', 'MEDIA', FALSE, NOW(), NOW()),
(12, 45, 'Solicita acompañamiento psicológico voluntariamente', 'ALTA', TRUE, NOW(), NOW()),
(13, 46, 'Dificultad para relacionarse con figuras de autoridad', 'BAJA', FALSE, NOW(), NOW()),
(14, 47, 'Alumno manifiesta tristeza constante', 'MEDIA', TRUE, NOW(), NOW()),
(15, 48, 'Se recomienda derivación por problemas de adicciones', 'ALTA', FALSE, NOW(), NOW());
